
apiVersion: v1
kind: Pod
metadata:
  name: csi-pod
  namespace: storage-demo
spec:
  containers:
    - name: app
      image: busybox
      command:
        - /bin/sh
        - -c
        - "while true; do echo $(date) >> /data/test.txt; sleep 10; done"
      volumeMounts:
        - name: mydata
          mountPath: /data
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
  volumes:
    - name: mydata
      persistentVolumeClaim:
        claimName: csi-pvc
