
apiVersion: v1
kind: Pod
metadata:
  name: pv-demo
  namespace: storage-demo
spec:
  containers:
    - name: app
      image: busybox
      command:
        - /bin/sh
        - -c
        - "date >> /mnt/storage/date.txt && sleep 3600"
      volumeMounts:
        - name: pv-storage
          mountPath: /mnt/storage
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pvc-hostpath
