name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform"
        required: true
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    name: terraform ${{ inputs.action }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        working-directory: terraform_local

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Save GitHub OIDC token to file
        shell: bash
        run: |
          response="$(
            curl --fail --silent --show-error \
              -H "Authorization: Bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
              "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=api%3A%2F%2FAzureADTokenExchange"
          )"

          jq -r '.value' <<< "$response" > github-oidc-token.jwt

      - name: Upload an Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          # Artifact name. If the `archive` input is `false`, the name of the file uploaded will be the artifact name.
          name: github-oidc-token.jwt
          # A file, directory or wildcard pattern that describes what to upload.
          path: github-oidc-token.jwt


      - name: Login to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Save Azure access token to file
        shell: bash
        run: |
          az account get-access-token \
            --resource https://management.azure.com/ \
            --query accessToken \
            --output tsv > azure-access-token.jwt

      - name: Upload an Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          # Artifact name. If the `archive` input is `false`, the name of the file uploaded will be the artifact name.
          name: azure-access-token.jwt
          # A file, directory or wildcard pattern that describes what to upload.
          path: azure-access-token.jwt


      - name: Show Azure Account Info
        run: az account show

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          if [ "${{ inputs.action }}" = "destroy" ]; then
            terraform plan -destroy -out=tfplan
          else
            terraform plan -out=tfplan
          fi

      - name: Terraform ${{ inputs.action }}
        run: terraform apply -auto-approve tfplan
